server: 
  port: 80

mybatis:  mapper-locations:  - classpath:mapper/*.xml
  
spring:  datasource:    url: dddddddddddddd
    username: dddddddddddddd
    password: dddddddddddddd
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
db: 
  hostIP: dddddddddddddd
  savePath: /db
  fileName: dbBeiFens.sql
  databaseName: room